[package]
name = "pigeons-site-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
copy_dir = "0.1.3"
serde = { version = "1.0.197", features = ["derive"] }
tera = "1.19.1"
