on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-go@v4"

      - name: "Install zs"
        run: "go install go.mills.io/zs@latest"

      - name: "Build static files"
        run: "zs build"

      - uses: "actions/upload-pages-artifact@v1"
        with:
          name: "github-pages"
          path: ".pub/"

  deploy:
    needs: "build"

    permissions:
      pages: "write"
      id-token: "write"

    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v2"
